services:
  tracker:
    build: ./tracker
    ports:
      - "9000:9000"
    restart: always

  groupmanager:
    build: ./groupmanager
    ports:
      - "8000:8000"
    restart: always

  router:
    build: ./router
    env_file:
      - .env
    depends_on:
      - tracker
      - groupmanager
    ports:
      - "8080:8080" # добавим порт, чтобы можно было обращаться к роутеру, если нужно
    restart: always