services:
  my_postgres:
    image: postgres:18.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1244
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always

  tracker:
    build: ./tracker
    ports:
      - "9000:9000"
    environment:
      - DB_HOST=my_postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=1244
    depends_on:
      - my_postgres
    restart: always

  groupmanager:
    build: ./groupmanager
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=my_postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=1244
    depends_on:
      - my_postgres  
    restart: always

  router:
    build: ./router
    env_file:
      - .env
    depends_on:
      - tracker
      - groupmanager
    ports:
      - "8080:8080" # добавим порт, чтобы можно было обращаться к роутеру, если нужно
    restart: always